version: 2.1

jobs:
  hello-job:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run:
          name: List directory contents
          command: ls -al
      - run:
          name: Check for package.json
          command: |
            if [ ! -f package.json ]; then
              echo "Unable to find your package.json file. Did you forget to set the app-dir parameter?"
              exit 1
            fi
      - run: echo "hello world"

workflows:
  my-workflow:
    jobs:
      - hello-job
